"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$env_var\
$sudo\
(\
- \
$memory_usage\
$package\
$custom\
$c\
$cpp\
$cmake\
$golang\
$python\
$nodejs\
$container\
)\
$fill\
$status\
$cmd_duration\
$time\
$line_break\
$shell\
$character"""

add_newline = true

[shell]
disabled = true

[fill]
symbol = " "

[os]
format = '[ $symbol]($style)'
# style = 'bright-white bg:black bold'
disabled = false
style = 'bright-white'

[username]
show_always = true
format = '[$user ]($style)'
# style_user = 'bright-white bg:black bold'
style_user = 'bright-white'

[time]
disabled = false
format = " [$time]($style) "
style = "yellow"

[sudo]
disabled = false
symbol = "󱕴"
format = '[$symbol]($style)'
style = 'blink red'

[cmd_duration]
min_time = 500
show_milliseconds = true
format = ' [$duration]($style) '


[c]
symbol = " "
format = '[ $symbol($version(-$name)) ]($style)'
style = "bg:cyan bright-white"
version_format = "${raw}"

[cpp]
symbol = " "
format = '[ $symbol($version(-$name)) ]($style)'
style = "bg:cyan bright-white"
version_format = "${raw}"

[cmake]
symbol = " "
format = '[ $symbol($version) ]($style)'
style = "bg:red bright-white"

[directory]
read_only = " 󰌾"
truncate_to_repo = true
repo_root_style = "green"
truncation_symbol = "../"
truncation_length = 3
format = '[ $path]($style)[$read_only]($read_only_style) '
repo_root_format = '[󰊢 $repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
home_symbol = "~"
use_logical_path = false

[git_branch]
symbol = " "
format = '[\($symbol$branch(:$remote_branch)\)]($style) '
style = "bright-green bold"

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "
format = '[ $symbol($version) ]($style)'
style = 'bg:blue bright-white'
version_format = "${raw}"

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛"
threshold = 60
disabled = false
format = '[ $symbol ${ram_pct} ]($style)'
style = "bg:purple bright-white"


[nodejs]
symbol = " "
format = "[ $symbol($version) ]($style)"
style = "bg:green bright-white bold"
version_format = "${raw}"


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = " "
format = '[ $symbol$version ]($style)'
style = "bg:yellow bright-white"
version_format = "${raw}"
display_private = true

[python]
symbol = " "
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bg:green"
version_format = "${raw}"


[status]
disabled = false
symbol = "️ "
success_symbol = " "
not_executable_symbol = " "
not_found_symbol = "? "
sigint_symbol = " "
success_style = "green"
failure_style = "red"
map_symbol = true
pipestatus = true
format = '[$symbol$status( $signal_name)]($style) '


[custom.docker-compose]
description = "Shows the docker symbol if the current directory has docker-compose files"
detect_files = [
    "docker-compose.yml",
    "docker-compose.yaml",
    "compose.yml",
    "compose.yaml",
]
command = "docker compose version --short"
symbol = "󰡨"
format = '[ $symbol $output ](bg:white blue)'


[custom.docker]
description = "Show the docker symbol if Dockerfile is present"
detect_files = ["Dockerfile"]
detect_extensions = ["Dockerfile"]
command = 'docker version --format "{{.Server.Version}}"'
symbol = "󰡨"
format = '[ $symbol $output ](bg:white blue)'
